title: Dino jump
hero_image: images/banner.png
description: Make a jumping game in this Code Club Arcade project.
listed: true
pdf: false
steps:
  - title: What you will make
  - title: Add the character and backdrop
    completion:
      - engaged
  - title: Make the character jump
  - title: Add obstacles
  - title: Make the obstacles move
    completion:
      - internal
  - title: Detect collisions and keep score
  - title: Test and tune your game
    completion:
      - external
  - title: Challenge
    challenge: true
